#!/usr/bin/env bash
#display to infinity and beyond indefinitely

#handle a SIGTERM and you can use (15) in place of SIGTERM
trap "echo 'I am invincible!!!'" SIGTERM

#print the message forever
while true;
do 
	echo "To infinity and beyond"
	sleep 2
done
	
