#!/usr/bin/env bash
#display to infinity and beyond indefinitely

#handle a SIGTERM
trap "echo 'I am invincible!!!'" 15

#print the message forever
while true;
do 
	echo "To infinity and beyond"
	sleep 2
done
	
